In [1]:
# Importing necessary imports
import os
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
sns.set()

In [3]:
df = pd.read_csv('kidney_disease.csv')[['age','wc','htn','dm','classification']]
df.head()

    age    wc  htn   dm classification
0  48.0  7800  yes  yes            ckd
1   7.0  6000   no   no            ckd
2  62.0  7500   no  yes            ckd
3  48.0  6700  yes   no            ckd
4  51.0  7300   no   no            ckd

In [4]:
df.isnull().sum()

age                 9
wc                105
htn                 2
dm                  2
classification      0
dtype: int64

In [5]:
from sklearn.impute import SimpleImputer
imp_mode = SimpleImputer(missing_values = np.nan, strategy='most_frequent')
df_imputed = pd.DataFrame(imp_mode.fit_transform(df))
df_imputed.columns = df.columns
df_imputed

      age    wc  htn   dm classification
0    48.0  7800  yes  yes            ckd
1     7.0  6000   no   no            ckd
2    62.0  7500   no  yes            ckd
3    48.0  6700  yes   no            ckd
4    51.0  7300   no   no            ckd
..    ...   ...  ...  ...            ...
395  55.0  6700   no   no         notckd
396  42.0  7800   no   no         notckd
397  12.0  6600   no   no         notckd
398  17.0  7200   no   no         notckd
399  58.0  6800   no   no         notckd

[400 rows x 5 columns]

In [6]:
df_imputed.isnull().sum()

age               0
wc                0
htn               0
dm                0
classification    0
dtype: int64

In [7]:

for i in df_imputed.columns:
    print("************************************", i ,  "****************************")
    print()
    print(set(df_imputed[i].tolist()))
    print()

************************************ age ****************************

{2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 11.0, 12.0, 14.0, 15.0, 17.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 32.0, 33.0, 34.0, 35.0, 36.0, 37.0, 38.0, 39.0, 40.0, 41.0, 42.0, 43.0, 44.0, 45.0, 46.0, 47.0, 48.0, 49.0, 50.0, 51.0, 52.0, 53.0, 54.0, 55.0, 56.0, 57.0, 58.0, 59.0, 60.0, 61.0, 62.0, 63.0, 64.0, 65.0, 66.0, 67.0, 68.0, 69.0, 70.0, 71.0, 72.0, 73.0, 74.0, 75.0, 76.0, 78.0, 79.0, 80.0, 81.0, 82.0, 83.0, 90.0}

************************************ wc ****************************

{'10900', '7100', '8800', '9700', '7500', '9800', '9000', '9200', '12200', '12500', '10500', '9300', '5200', '11900', '8600', '11200', '4500', '7400', '10200', '7700', '4300', '13600', '3800', '4700', '5400', '15700', '6900', '6700', '5800', '11400', '16700', '4200', '10400', '9900', '8300', '11000', '7000', '14600', '8100', '15200', '2200', '5700', '12800', '5100', '14900', '7900', '6000', '19100', '13200', '26400', '16300', '\t6200', '12700', '11500', '12400', '10800', '7300', '9100', '6600', '9600', '7800', '\t8400', '5000', '10300', '11300', '2600', '5900', '9400', '8000', '12300', '\t?', '8500', '8200', '18900', '6500', '5600', '6200', '10700', '7200', '6300', '4100', '6800', '12000', '5300', '21600', '8400', '6400', '5500', '11800', '9500', '12100', '4900'}

************************************ htn ****************************

{'yes', 'no'}

************************************ dm ****************************

{'\tyes', '\tno', 'yes', 'no', ' yes'}

************************************ classification ****************************

{'ckd\t', 'notckd', 'ckd'}

In [8]:
df_imputed['classification'] = df_imputed['classification'].apply(lambda x:'ckd' if x=='ckd\t' else x)

df_imputed['dm'] = df_imputed['dm'].apply(lambda x:'yes' if x=='\tyes' else x)
df_imputed['dm'] = df_imputed['dm'].apply(lambda x:'no' if x=='\tno' else x)
df_imputed['dm'] = df_imputed['dm'].apply(lambda x:'yes' if x==' yes' else x)

df_imputed['wc'] = df_imputed['wc'].apply(lambda x:'6200' if x=='\t6200' else x)
df_imputed['wc'] = df_imputed['wc'].apply(lambda x:'8400' if x=='\t8400' else x)
df_imputed['wc'] = df_imputed['wc'].apply(lambda x:'9800' if x=='\t?' else x)

In [11]:

for i in df_imputed.columns:
    print("************************************", i ,  "****************************")
    print()
    print(set(df_imputed[i].tolist()))
    print()

************************************ age ****************************

{2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 11.0, 12.0, 14.0, 15.0, 17.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 32.0, 33.0, 34.0, 35.0, 36.0, 37.0, 38.0, 39.0, 40.0, 41.0, 42.0, 43.0, 44.0, 45.0, 46.0, 47.0, 48.0, 49.0, 50.0, 51.0, 52.0, 53.0, 54.0, 55.0, 56.0, 57.0, 58.0, 59.0, 60.0, 61.0, 62.0, 63.0, 64.0, 65.0, 66.0, 67.0, 68.0, 69.0, 70.0, 71.0, 72.0, 73.0, 74.0, 75.0, 76.0, 78.0, 79.0, 80.0, 81.0, 82.0, 83.0, 90.0}

************************************ wc ****************************

{12800.0, 4100.0, 8200.0, 12300.0, 7700.0, 11800.0, 7200.0, 11300.0, 2600.0, 6700.0, 10800.0, 14900.0, 6200.0, 10300.0, 5700.0, 9800.0, 5200.0, 9300.0, 4700.0, 21600.0, 8800.0, 4200.0, 8300.0, 12400.0, 7800.0, 11900.0, 7300.0, 11400.0, 6800.0, 10900.0, 2200.0, 6300.0, 19100.0, 10400.0, 5800.0, 9900.0, 5300.0, 9400.0, 4300.0, 8400.0, 12500.0, 3800.0, 7900.0, 12000.0, 7400.0, 11500.0, 6900.0, 11000.0, 6400.0, 10500.0, 14600.0, 5900.0, 5400.0, 9500.0, 13600.0, 26400.0, 4900.0, 9000.0, 8500.0, 16700.0, 8000.0, 12100.0, 7500.0, 15700.0, 7000.0, 15200.0, 6500.0, 6000.0, 5500.0, 9600.0, 5000.0, 9100.0, 13200.0, 4500.0, 8600.0, 12700.0, 8100.0, 12200.0, 16300.0, 7100.0, 11200.0, 6600.0, 10700.0, 18900.0, 10200.0, 5600.0, 9700.0, 5100.0, 9200.0}

************************************ htn ****************************

{'yes', 'no'}

************************************ dm ****************************

{'yes', 'no'}

************************************ classification ****************************

{'notckd', 'ckd'}

In [10]:
df_imputed['wc'] = df_imputed['wc'].apply(lambda x: float(x))

In [12]:
# Label encoder
from sklearn import preprocessing
df_enco = df_imputed.apply(preprocessing.LabelEncoder().fit_transform)
df_enco

     age  wc  htn  dm  classification
0     40  35    1   1               0
1      5  19    0   0               0
2     54  33    0   1               0
3     40  25    1   0               0
4     43  31    0   0               0
..   ...  ..  ...  ..             ...
395   47  25    0   0               1
396   34  35    0   0               1
397    8  24    0   0               1
398   11  30    0   0               1
399   50  26    0   0               1

[400 rows x 5 columns]

In [13]:
x = df_enco.drop(['classification'], axis=1)
y = df_enco['classification']

In [14]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler((-1,1))
x = scaler.fit_transform(x)
x

array([[ 0.06666667, -0.20454545,  1.        ,  1.        ],
       [-0.86666667, -0.56818182, -1.        , -1.        ],
       [ 0.44      , -0.25      , -1.        ,  1.        ],
       ...,
       [-0.78666667, -0.45454545, -1.        , -1.        ],
       [-0.70666667, -0.31818182, -1.        , -1.        ],
       [ 0.33333333, -0.40909091, -1.        , -1.        ]])

In [15]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42, stratify=y)

In [16]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(max_depth=4, random_state=10)
model.fit(x_train, y_train)

RandomForestClassifier(max_depth=4, random_state=10)

In [17]:
from sklearn.metrics import accuracy_score
pred_cv = model.predict(x_test)
accuracy_score(y_test, pred_cv)

0.8125

# Deployment part

In [18]:
# saving the model
import pickle
pickle_out = open("classifier.pkl", mode="wb")
pickle.dump(model, pickle_out)
pickle_out.close()

In [19]:
df_enco.columns

Index(['age', 'wc', 'htn', 'dm', 'classification'], dtype='object')

In [20]:
df_imputed.head(2)

    age      wc  htn   dm classification
0  48.0  7800.0  yes  yes            ckd
1   7.0  6000.0   no   no            ckd

In [21]:
%%writefile app.py
import pickle

import streamlit as st # frontend code
# loading the trained model
pickle_in = open('classifier.pkl','rb')
classifier = pickle.load(pickle_in)

@st.cache()

def prediction(age, wc, htn, dm):
    if htn =='no':
        htn=0
    else:
        htn=1
        
    if dm=='no':
        dm =0
    else:
        dm = 1
        
    # making prediction
    prediction = classifier.predict(
    [[age, wc, htn, dm]])
        
    if prediction == 0:
        pred='Kindey Disease not detected'
    else:
        pred = 'Kindey Disease found'
    
    return pred
    
    
# Write streamlit function now
def main():
    html_temp= """
    <div style ="background-color:cyan:padding:13px">
    <h1 style="color:black;text-align:center;">Kidney Disease Prediction</h1>
    </div>
    """
    st.markdown(html_temp, unsafe_allow_html=True)
    htn = st.selectbox('htn',("no","yes"))
    dm= st.selectbox('dm status',('no','yes'))
    age=st.number_input("Age")
    wc=st.number_input("WC")
    RESULT=""
    
    
    # WHEN 'PREDICT' is clicked, make the prediction and store it
    if st.button("Predict"):
        result = prediction(age, wc, htn, dm)
        st.success("Report Results: {}".format(result))
        
if __name__=='__main__':
    main()

Writing app.py